name: Deploy Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Sync PySpark Code to Databricks
        env:
          # This is where the robot pulls the secret keys we just saved!
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "Connecting to Databricks and creating project folder..."
          databricks workspace mkdirs /Shared/airflow_project || true
          
          echo "Uploading Pipeline Layers..."
          databricks workspace import -l PYTHON -o 01_bronze_ingestion_v2.py /Shared/airflow_project/01_bronze_ingestion_v2.py
          databricks workspace import -l PYTHON -o 02_silver_cleansing_v2.py /Shared/airflow_project/02_silver_cleansing_v2.py
          databricks workspace import -l PYTHON -o 03_gold_layer_v2 /Shared/airflow_project/03_gold_layer_v2.py
          
          echo "Sync Complete!"